#+TITLE: Running =larf=

* Overview

LARF calculations are run through the =larf= command line.  
Each possible calculation is in a particular category and has a specific, associated sub-command.
Calculations consume and produce zero or more /results/.  
A result consist of zero or more /arrays/ produced by the calculation and a collection or input /parameters/.
Results are stored in an Sqlite3 database file (see doc on [[./export.org][exporting]] for how to get results in other formats).  
Each new result is given an unique result ID number.
This number is used to look up a result and provide it as input to a subsequent calculation.
Results can be exported from the database file in various formats including visualization.
Many calculations rely on a configuration file to specify their input parameters.
Be default the configuration file =larf.cfg= is used and the database file =larf.db= is used.
Either file may be explicitly specified to the =larf= command line program.

* Example

As an example, the provided =larf.cfg= is used to calculate a drift velocity field for a geometry of a simple parallel plane capacitor.

#+BEGIN_EXAMPLE
  $ rm -f larf.db
  $ larf mesh capacitor
  $ larf boundary -m 1 capdrift
  $ larf raster -b 2 special
  $ larf velocity -r 3 special
  $ larf list

  result:1 parent:0 2016-07-01 15:30:57.367264 type:mesh       name:capacitor   
    array:1 type:domains      name:domains      dtype:float64  shape:(4240,)
    array:2 type:points       name:points       dtype:float64  shape:(2124, 3)
    array:3 type:triangles    name:triangles    dtype:int64    shape:(4240, 3)

  result:2 parent:1 2016-07-01 15:31:24.955436 type:boundary   name:capdrift    
    array:4 type:coeff        name:dirichlet    dtype:float64  shape:(2124,)
    array:5 type:coeff        name:neumann      dtype:float64  shape:(4240,)

  result:3 parent:2 2016-07-01 15:32:34.170297 type:raster     name:special     
    array:6 type:gscalar      name:potential    dtype:float64  shape:(40, 3, 40)
    array:7 type:mgrid        name:domain       dtype:float64  shape:(3, 40, 3, 40)

  result:4 parent:3 2016-07-01 15:34:08.496289 type:velocity   name:special     
    array:8 type:mgrid        name:domain       dtype:float64  shape:(3, 40, 3, 40)
    array:9 type:gvector      name:velocity     dtype:float64  shape:(3, 40, 3, 40)
#+END_EXAMPLE

